// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_bloc_training/test/series_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_bloc_training/models/series.dart' as _i3;
import 'package:flutter_bloc_training/models/series_list_item.dart' as _i2;
import 'package:flutter_bloc_training/repositories/series_repository.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSeriesListItem_0 extends _i1.SmartFake
    implements _i2.SeriesListItem {
  _FakeSeriesListItem_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSeries_1 extends _i1.SmartFake implements _i3.Series {
  _FakeSeries_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeriesRepository extends _i1.Mock implements _i4.SeriesRepository {
  MockSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  String get apiToken =>
      (super.noSuchMethod(
            Invocation.getter(#apiToken),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#apiToken),
            ),
          )
          as String);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i6.Future<List<_i2.SeriesListItem>> fetchSeries(int? page) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSeries, [page]),
            returnValue: _i6.Future<List<_i2.SeriesListItem>>.value(
              <_i2.SeriesListItem>[],
            ),
          )
          as _i6.Future<List<_i2.SeriesListItem>>);

  @override
  _i6.Future<_i2.SeriesListItem> updateSeries(_i2.SeriesListItem? series) =>
      (super.noSuchMethod(
            Invocation.method(#updateSeries, [series]),
            returnValue: _i6.Future<_i2.SeriesListItem>.value(
              _FakeSeriesListItem_0(
                this,
                Invocation.method(#updateSeries, [series]),
              ),
            ),
          )
          as _i6.Future<_i2.SeriesListItem>);

  @override
  _i6.Future<void> deleteSeries(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSeries, [id]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.SeriesListItem> createSeries(_i2.SeriesListItem? series) =>
      (super.noSuchMethod(
            Invocation.method(#createSeries, [series]),
            returnValue: _i6.Future<_i2.SeriesListItem>.value(
              _FakeSeriesListItem_0(
                this,
                Invocation.method(#createSeries, [series]),
              ),
            ),
          )
          as _i6.Future<_i2.SeriesListItem>);

  @override
  _i6.Future<_i3.Series> showSeries(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#showSeries, [id]),
            returnValue: _i6.Future<_i3.Series>.value(
              _FakeSeries_1(this, Invocation.method(#showSeries, [id])),
            ),
          )
          as _i6.Future<_i3.Series>);
}
